package provider

// registry_data.go holds the curated chat-provider registry.
// Originally generated from 9router open-sse/providers/registry/; pruned to
// the curated KEEP set in Phase 36 (registry IDs stay stable — no DB/alias
// migration; display names are vendor-official). Media providers
// (internal/media) are a separate registry and were out of scope.

func init() {
	Registry = make(map[string]ProviderInfo, 40)

	Registry["alicode-intl"] = ProviderInfo{
		ID: "alicode-intl", Name: "Alibaba (Intl)",
		Alias: "alicode-intl", Aliases: []string{"alicode-intl"},
		BaseURL: "https://coding-intl.dashscope.aliyuncs.com/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 10,
		Brand: "Alibaba", Region: "intl",
		Color:    "#FF6A00",
		Website:  "https://www.alibabacloud.com/product/coding",
		Icon:     "cloud",
		TextIcon: "ALi",
	}
	Registry["alicode"] = ProviderInfo{
		ID: "alicode", Name: "Alibaba (China)",
		Alias: "alicode", Aliases: []string{"alicode"},
		BaseURL: "https://coding.dashscope.aliyuncs.com/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 20,
		Brand: "Alibaba", Region: "cn",
		Color:    "#FF6A00",
		Website:  "https://bailian.console.aliyun.com",
		Icon:     "cloud",
		TextIcon: "ALi",
	}
	Registry["anthropic"] = ProviderInfo{
		ID: "anthropic", Name: "Anthropic",
		Alias: "anthropic", Aliases: []string{"anthropic"},
		BaseURL: "https://api.anthropic.com/v1/messages",
		APIType: "anthropic", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 30,
		Color:     "#D97757",
		Website:   "https://console.anthropic.com",
		Icon:      "smart_toy",
		TextIcon:  "AN",
		APIKeyURL: "https://console.anthropic.com/settings/keys",
		Headers: map[string]string{
			"anthropic-version": "2023-06-01",
			"Anthropic-Beta":    "claude-code-20250219,interleaved-thinking-2025-05-14",
		},
		AuthHeader: "x-api-key",
		AuthScheme: "raw",
	}
	Registry["antigravity"] = ProviderInfo{
		ID: "antigravity", Name: "Google Antigravity",
		Alias: "ag", Aliases: []string{"ag"},
		BaseURL: "",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth"}, Priority: 20,
		Color:        "#F59E0B",
		Website:      "https://antigravity.google",
		Icon:         "rocket_launch",
		TokenURL:     "https://oauth2.googleapis.com/token",
		AuthorizeURL: "https://accounts.google.com/o/oauth2/v2/auth",
		ClientID:     "1071006060591-tmhssin2h21lcre235vtolojh4g403ep.apps.googleusercontent.com",
	}
	Registry["cerebras"] = ProviderInfo{
		ID: "cerebras", Name: "Cerebras",
		Alias: "cerebras", Aliases: []string{"cerebras"},
		BaseURL: "https://api.cerebras.ai/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 60,
		Color:     "#FF4F00",
		Website:   "https://www.cerebras.ai",
		Icon:      "memory",
		TextIcon:  "CB",
		APIKeyURL: "https://cloud.cerebras.ai/platform",
	}
	Registry["claude"] = ProviderInfo{
		ID: "claude", Name: "Claude Code",
		Alias: "cc", Aliases: []string{"cc"},
		BaseURL: "https://api.anthropic.com/v1/messages",
		APIType: "anthropic", AuthType: "oauth",
		// Phase 36 T4: dual-auth (OAuth preferred, API key fallback —
		// same selection pattern as xai/kimi).
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 10,
		Color:        "#D97757",
		Website:      "https://claude.ai",
		Icon:         "smart_toy",
		APIKeyURL:    "https://console.anthropic.com/settings/keys",
		TokenURL:     "https://api.anthropic.com/v1/oauth/token",
		AuthorizeURL: "https://claude.ai/oauth/authorize",
		ClientID:     "9d1c250a-e61b-44d9-88ed-5944d1962f5e",
	}
	Registry["codebuddy-cn"] = ProviderInfo{
		ID: "codebuddy-cn", Name: "CodeBuddy (CN)",
		Alias: "cbcn", Aliases: []string{"cbcn"},
		BaseURL: "https://copilot.tencent.com/v2/chat/completions",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 90,
		Brand: "CodeBuddy", Region: "cn",
		Color:    "#006EFF",
		Website:  "https://copilot.tencent.com",
		Icon:     "smart_toy",
		TokenURL: "https://copilot.tencent.com/v2/plugin/auth/token",
		Headers: map[string]string{
			"User-Agent":          "CLI/2.108.1 CodeBuddy/2.108.1",
			"X-Product":           "SaaS",
			"X-IDE-Type":          "CLI",
			"X-IDE-Name":          "CLI",
			"x-requested-with":    "XMLHttpRequest",
			"x-codebuddy-request": "1",
		},
		ForceStream:    true,
		ThinkingFormat: "openai",
	}
	Registry["codebuddy-intl"] = ProviderInfo{
		ID: "codebuddy-intl", Name: "CodeBuddy (Intl)",
		Alias: "cbai", Aliases: []string{"cbai"},
		BaseURL: "https://www.codebuddy.ai/v2/chat/completions",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 90,
		Brand: "CodeBuddy", Region: "intl",
		Color:    "#006EFF",
		Website:  "https://www.codebuddy.ai",
		Icon:     "smart_toy",
		TextIcon: "CB",
		TokenURL: "https://www.codebuddy.ai/v2/plugin/auth/token",
		Headers: map[string]string{
			"User-Agent":          "IDE/2.108.1 CodeBuddy/2.108.1",
			"X-Product":           "SaaS",
			"X-IDE-Type":          "IDE",
			"X-IDE-Name":          "IDE",
			"x-requested-with":    "XMLHttpRequest",
			"x-codebuddy-request": "1",
		},
		ForceStream:    true,
		ThinkingFormat: "openai",
	}
	Registry["codex"] = ProviderInfo{
		ID: "codex", Name: "OpenAI Codex",
		Alias: "cx", Aliases: []string{"cx"},
		BaseURL: "https://chatgpt.com/backend-api/codex/responses",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 30,
		Color:        "#3B82F6",
		Website:      "https://chatgpt.com/codex",
		Icon:         "code",
		APIKeyURL:    "https://platform.openai.com/api-keys",
		TokenURL:     "https://auth.openai.com/oauth/token",
		AuthorizeURL: "https://auth.openai.com/oauth/authorize",
		ClientID:     "app_EMoamEEZ73f0CkXaXp7hrann",
	}
	Registry["cursor"] = ProviderInfo{
		ID: "cursor", Name: "Cursor",
		Alias: "cu", Aliases: []string{"cu"},
		BaseURL: "https://api2.cursor.sh",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth"}, Priority: 50,
		Color:   "#00D4AA",
		Website: "https://cursor.com",
		Icon:    "edit_note",
	}
	Registry["deepseek"] = ProviderInfo{
		ID: "deepseek", Name: "DeepSeek",
		Alias: "deepseek", Aliases: []string{"deepseek", "ds"},
		BaseURL: "https://api.deepseek.com/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 110,
		Color:     "#4D6BFE",
		Website:   "https://deepseek.com",
		Icon:      "bolt",
		TextIcon:  "DS",
		APIKeyURL: "https://platform.deepseek.com/api_keys",
	}
	Registry["gemini"] = ProviderInfo{
		ID: "gemini", Name: "Gemini",
		Alias: "gemini", Aliases: []string{"gemini"},
		BaseURL: "https://generativelanguage.googleapis.com/v1beta/models",
		APIType: "gemini", AuthType: "api-key",
		Category: "freeTier", AuthModes: []string{"api-key"}, Priority: 50,
		Color:     "#4285F4",
		Website:   "https://ai.google.dev",
		Icon:      "diamond",
		TextIcon:  "GE",
		HasFree:   true,
		APIKeyURL: "https://aistudio.google.com/app/apikey",
		ClientID:  "681255809395-oo8ft2oprdrnp9e3aqf6av3hmdib135j.apps.googleusercontent.com",
		// 9router gemini.js transport.auth.apiKey: API keys go in the
		// x-goog-api-key header (raw), not the ?key= query param.
		AuthHeader: "x-goog-api-key",
		AuthScheme: "raw",
		// Live model catalog: the base IS the models list (auth = ?key=).
		ModelsURL:  "https://generativelanguage.googleapis.com/v1beta/models",
		ModelsAuth: "query",
	}
	Registry["github"] = ProviderInfo{
		ID: "github", Name: "GitHub Copilot",
		Alias: "gh", Aliases: []string{"gh"},
		BaseURL: "https://api.githubcopilot.com/chat/completions",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth"}, Priority: 40,
		Color:         "#333333",
		Website:       "https://github.com/features/copilot",
		Icon:          "code",
		DeviceCodeURL: "https://github.com/login/device/code",
		TokenURL:      "https://github.com/login/oauth/access_token",
		AuthorizeURL:  "https://github.com/login/oauth/authorize",
		ClientID:      "Iv1.b507a08c87ecfe98",
		Headers: map[string]string{
			"copilot-integration-id":              "vscode-chat",
			"editor-version":                      "vscode/1.110.0",
			"editor-plugin-version":               "copilot-chat/0.38.0",
			"user-agent":                          "GitHubCopilotChat/0.38.0",
			"openai-intent":                       "conversation-panel",
			"x-github-api-version":                "2025-04-01",
			"x-vscode-user-agent-library-version": "electron-fetch",
			"X-Initiator":                         "user",
		},
	}
	Registry["glm-cn"] = ProviderInfo{
		ID: "glm-cn", Name: "GLM (China)",
		Alias: "glm-cn", Aliases: []string{"glm-cn"},
		BaseURL: "https://open.bigmodel.cn/api/coding/paas/v4/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 130,
		Brand: "GLM", Region: "cn",
		Color:    "#DC2626",
		Website:  "https://open.bigmodel.cn",
		Icon:     "code",
		TextIcon: "GC",
	}
	Registry["glm"] = ProviderInfo{
		ID: "glm", Name: "GLM Coding",
		Alias: "glm", Aliases: []string{"glm"},
		BaseURL: "https://api.z.ai/api/anthropic/v1/messages",
		APIType: "anthropic", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 140,
		Brand: "GLM", Region: "intl",
		Color:     "#2563EB",
		Website:   "https://open.bigmodel.cn",
		Icon:      "code",
		TextIcon:  "GL",
		APIKeyURL: "https://open.bigmodel.cn/usercenter/apikeys",
		// 9router glm.js transport: claude /coding endpoint, ?beta=true suffix,
		// x-api-key raw auth + CLAUDE_API_HEADERS.
		URLSuffix:  "?beta=true",
		Headers:    map[string]string{"anthropic-version": "2023-06-01", "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14"},
		AuthHeader: "x-api-key",
		AuthScheme: "raw",
	}
	Registry["grok-cli"] = ProviderInfo{
		ID: "grok-cli", Name: "Grok Build",
		Alias: "gcli", Aliases: []string{"gcli", "grok-build", "gb"},
		BaseURL: "",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth"}, Priority: 275,
		Color:         "#1DA1F2",
		Website:       "https://x.ai",
		Icon:          "auto_awesome",
		TextIcon:      "GC",
		DeviceCodeURL: "https://auth.x.ai/oauth2/device/code",
		TokenURL:      "https://auth.x.ai/oauth2/token",
		ClientID:      "b1a00492-073a-47ea-816f-4c329264a828",
	}
	Registry["groq"] = ProviderInfo{
		ID: "groq", Name: "Groq",
		Alias: "groq", Aliases: []string{"groq"},
		BaseURL: "https://api.groq.com/openai/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 60,
		Color:       "#F55036",
		Website:     "https://groq.com",
		Icon:        "speed",
		TextIcon:    "GQ",
		HasFree:     true,
		APIKeyURL:   "https://console.groq.com/keys",
		ValidateURL: "https://api.groq.com/openai/v1/models",
	}
	Registry["kimi"] = ProviderInfo{
		ID: "kimi", Name: "Kimi Code",
		Alias: "kimi", Aliases: []string{"kimi", "kimi-coding", "kmc"},
		BaseURL: "https://api.kimi.com/coding/v1/messages",
		APIType: "anthropic", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 170,
		Color:         "#1E3A8A",
		Website:       "https://kimi.moonshot.cn",
		Icon:          "psychology",
		TextIcon:      "KM",
		APIKeyURL:     "https://platform.moonshot.ai/console/api-keys",
		DeviceCodeURL: "https://auth.kimi.com/api/oauth/device_authorization",
		TokenURL:      "https://auth.kimi.com/api/oauth/token",
		ClientID:      "17e5f671-d194-4dfb-9706-5516cb48c098",
		// 9router#2881: platform API keys (platform.kimi.ai) use the general
		// Moonshot OpenAI-compatible endpoint, not the /coding/ Anthropic one.
		ApiKeyBaseURL: "https://api.moonshot.cn/v1",
		ApiKeyAPIType: "openai",
		// Primary (OAuth) transport: claude /coding endpoint, x-api-key raw auth
		// + X-Msh-* fingerprint headers (9router kimi.js transport block).
		URLSuffix:  "?beta=true",
		Headers:    map[string]string{"anthropic-version": "2023-06-01", "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14"},
		AuthHeader: "x-api-key",
		AuthScheme: "raw",
		AuthHooks:  []string{"kimiHeaders"},
	}
	Registry["minimax-cn"] = ProviderInfo{
		ID: "minimax-cn", Name: "Minimax (China)",
		Alias: "minimax-cn", Aliases: []string{"minimax-cn"},
		BaseURL: "https://api.minimaxi.com/anthropic/v1/messages",
		APIType: "anthropic", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 190,
		Brand: "MiniMax", Region: "cn",
		Color:     "#DC2626",
		Website:   "https://www.minimaxi.com",
		Icon:      "memory",
		TextIcon:  "MC",
		APIKeyURL: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
		// 9router minimax-cn.js transport: claude endpoint, ?beta=true,
		// x-api-key raw auth + CLAUDE_API_HEADERS.
		URLSuffix:  "?beta=true",
		Headers:    map[string]string{"anthropic-version": "2023-06-01", "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14"},
		AuthHeader: "x-api-key",
		AuthScheme: "raw",
	}
	Registry["minimax"] = ProviderInfo{
		ID: "minimax", Name: "Minimax Coding",
		Alias: "minimax", Aliases: []string{"minimax"},
		BaseURL: "https://api.minimax.io/anthropic/v1/messages",
		APIType: "anthropic", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 90,
		Brand: "MiniMax", Region: "intl",
		Color:     "#7C3AED",
		Website:   "https://www.minimaxi.com",
		Icon:      "memory",
		TextIcon:  "MM",
		APIKeyURL: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
		// 9router minimax.js transport: claude endpoint, ?beta=true,
		// x-api-key raw auth + CLAUDE_API_HEADERS.
		URLSuffix:  "?beta=true",
		Headers:    map[string]string{"anthropic-version": "2023-06-01", "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14"},
		AuthHeader: "x-api-key",
		AuthScheme: "raw",
	}
	Registry["nvidia"] = ProviderInfo{
		ID: "nvidia", Name: "NVIDIA NIM",
		Alias: "nvidia", Aliases: []string{"nvidia"},
		BaseURL: "https://integrate.api.nvidia.com/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "freeTier", AuthModes: []string{"api-key"}, Priority: 20,
		Color:     "#76B900",
		Website:   "https://developer.nvidia.com/nim",
		Icon:      "developer_board",
		TextIcon:  "NV",
		HasFree:   true,
		APIKeyURL: "https://build.nvidia.com/settings/api-keys",
	}
	Registry["openai"] = ProviderInfo{
		ID: "openai", Name: "OpenAI",
		Alias: "openai", Aliases: []string{"openai"},
		BaseURL: "https://api.openai.com/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 30,
		Color:       "#10A37F",
		Website:     "https://platform.openai.com",
		Icon:        "auto_awesome",
		TextIcon:    "OA",
		APIKeyURL:   "https://platform.openai.com/api-keys",
		ForceStream: true,
	}
	Registry["opencode"] = ProviderInfo{
		ID: "opencode", Name: "OpenCode",
		Alias: "oc", Aliases: []string{"oc", "opencode-go", "ocg"},
		BaseURL: "https://opencode.ai/zen/v1/chat/completions",
		APIType: "openai", AuthType: "none",
		Category: "free", AuthModes: []string{"none", "api-key"}, Priority: 40,
		Color:    "#E87040",
		Website:  "https://opencode.ai",
		Icon:     "terminal",
		TextIcon: "OC",
		HasFree:  true,
		NoAuth:   true,
		Headers:  map[string]string{"x-opencode-client": "desktop"},
		// Public catalog (9router modelsFetcher opencode-free).
		ModelsURL:  "https://opencode.ai/zen/v1/models",
		ModelsAuth: "none",
	}
	Registry["openrouter"] = ProviderInfo{
		ID: "openrouter", Name: "OpenRouter",
		Alias: "openrouter", Aliases: []string{"openrouter"},
		BaseURL: "https://openrouter.ai/api/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "freeTier", AuthModes: []string{"api-key"}, Priority: 10,
		Color:     "#F97316",
		Website:   "https://openrouter.ai",
		Icon:      "router",
		TextIcon:  "OR",
		HasFree:   true,
		APIKeyURL: "https://openrouter.ai/settings/keys",
	}
	Registry["qoder"] = ProviderInfo{
		ID: "qoder", Name: "Qoder",
		Alias: "qd", Aliases: []string{"qd"},
		BaseURL: "https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation",
		APIType: "openai", AuthType: "oauth",
		// Phase 36 T5 (9router@9c9dd7b1): re-enabled OAuth + PAT (apikey)
		// auth. PATs (pt-...) are exchanged for short-lived job tokens before
		// COSY signing.
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 30,
		Color:         "#EC4899",
		Website:       "https://qoder.com",
		Icon:          "water_drop",
		HasFree:       true,
		AuthHint:      "Personal Access Token (pt-...) from https://qoder.com/account/integrations",
		DeviceCodeURL: "https://openapi.qoder.sh/api/v1/deviceToken/poll",
		LoginURL:      "https://qoder.com/device/selectAccounts",
	}
	Registry["tencent"] = ProviderInfo{
		ID: "tencent", Name: "Tencent Hunyuan",
		Alias: "hunyuan", Aliases: []string{"hunyuan", "tencent-hunyuan"},
		BaseURL: "https://api.hunyuan.cloud.tencent.com/v1/chat/completions",
		APIType: "openai", AuthType: "api-key",
		Category: "apikey", AuthModes: []string{"api-key"}, Priority: 130,
		Color:       "#0052D9",
		Website:     "https://cloud.tencent.com/product/hunyuan",
		Icon:        "cloud",
		TextIcon:    "HY",
		ValidateURL: "https://api.hunyuan.cloud.tencent.com/v1/models",
	}
	Registry["vertex"] = ProviderInfo{
		ID: "vertex", Name: "Vertex AI",
		Alias: "vertex", Aliases: []string{"vertex", "vx"},
		BaseURL: "https://aiplatform.googleapis.com",
		APIType: "openai", AuthType: "api-key",
		Category: "freeTier", AuthModes: []string{"api-key"}, Priority: 40,
		Color:    "#4285F4",
		Website:  "https://cloud.google.com/vertex-ai",
		Icon:     "cloud",
		TextIcon: "VX",
	}
	Registry["xai"] = ProviderInfo{
		ID: "xai", Name: "xAI (Grok)",
		Alias: "xai", Aliases: []string{"xai"},
		BaseURL: "https://api.x.ai/v1/chat/completions",
		APIType: "openai", AuthType: "oauth",
		Category: "oauth", AuthModes: []string{"oauth", "api-key"}, Priority: 280,
		Color:        "#1DA1F2",
		Website:      "https://x.ai",
		Icon:         "auto_awesome",
		TextIcon:     "XA",
		APIKeyURL:    "https://console.x.ai",
		AuthorizeURL: "https://auth.x.ai/oauth2/authorize",
		TokenURL:     "https://auth.x.ai/oauth2/token",
		ClientID:     "b1a00492-073a-47ea-816f-4c329264a828",
	}

	aliasMap = buildAliasMap()
}
