package provider

// registry_models.go holds the static model catalogs for the curated chat
// registry (Phase 36). Synced from 9router open-sse/providers/registry/ —
// qoder's list follows the realigned aliases from 9router@9c9dd7b1.
// Live catalog fetches (Phase 36 T6) override these; they remain the offline
// fallback.

// ModelRef is a single model entry (id + display name) from the upstream registry.
type ModelRef struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// RegistryModels maps provider id -> its known model list from the 9router registry.
var RegistryModels = map[string][]ModelRef{
	"alicode":        {{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "qwen3-max-2026-01-23", Name: "Qwen3 Max"}, {ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"}, {ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "glm-4.7", Name: "GLM 4.7"}},
	"alicode-intl":   {{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"}, {ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "glm-4.7", Name: "GLM 4.7"}},
	"anthropic":      {{ID: "claude-opus-5-20260701", Name: "Claude Opus 5"}, {ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"}, {ID: "claude-opus-4-20250514", Name: "Claude Opus 4"}, {ID: "claude-3-5-sonnet-20241022", Name: "Claude 3.5 Sonnet"}},
	"antigravity":    {{ID: "gemini-3-flash-agent", Name: "Gemini 3.5 Flash (High)"}, {ID: "gemini-3.5-flash-low", Name: "Gemini 3.5 Flash (Medium)"}, {ID: "gemini-3.5-flash-extra-low", Name: "Gemini 3.5 Flash (Low)"}, {ID: "gemini-pro-agent", Name: "Gemini 3.1 Pro (High)"}, {ID: "gemini-3.1-pro-low", Name: "Gemini 3.1 Pro (Low)"}, {ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6 (Thinking)"}, {ID: "claude-opus-4-6-thinking", Name: "Claude Opus 4.6 (Thinking)"}, {ID: "gpt-oss-120b-medium", Name: "GPT-OSS 120B (Medium)"}, {ID: "gemini-3-flash", Name: "Gemini 3 Flash"}, {ID: "gemini-3.1-flash-image", Name: "Gemini 3.1 Flash (Image)"}},
	"cerebras":       {{ID: "gpt-oss-120b", Name: "GPT OSS 120B"}, {ID: "zai-glm-4.7", Name: "ZAI GLM 4.7"}, {ID: "llama-3.3-70b", Name: "Llama 3.3 70B"}, {ID: "llama-4-scout-17b-16e-instruct", Name: "Llama 4 Scout"}, {ID: "qwen-3-235b-a22b-instruct-2507", Name: "Qwen3 235B A22B"}, {ID: "qwen-3-32b", Name: "Qwen3 32B"}},
	"claude":         {{ID: "claude-opus-5", Name: "Claude Opus 5"}, {ID: "claude-fable-5", Name: "Claude Fable 5"}, {ID: "claude-sonnet-5", Name: "Claude Sonnet 5"}, {ID: "claude-haiku-4-5-20251001", Name: "Claude 4.5 Haiku"}},
	"codebuddy-cn":   {{ID: "glm-5.2", Name: "GLM-5.2"}, {ID: "glm-5.1", Name: "GLM-5.1"}, {ID: "glm-5.0", Name: "GLM-5.0"}, {ID: "glm-5.0-turbo", Name: "GLM-5.0-Turbo"}, {ID: "glm-5v-turbo", Name: "GLM-5v-Turbo"}, {ID: "glm-4.7", Name: "GLM-4.7"}, {ID: "minimax-m3", Name: "MiniMax-M3"}, {ID: "minimax-m2.7", Name: "MiniMax-M2.7"}, {ID: "kimi-k2.7", Name: "Kimi-K2.7-Code"}, {ID: "kimi-k2.6", Name: "Kimi-K2.6"}, {ID: "kimi-k2.5", Name: "Kimi-K2.5"}, {ID: "hy3-preview", Name: "Hy3 Preview"}, {ID: "deepseek-v4-pro", Name: "DeepSeek-V4-Pro"}, {ID: "deepseek-v4-flash", Name: "DeepSeek-V4-Flash"}, {ID: "deepseek-v3-2-volc", Name: "DeepSeek-V3.2"}},
	"codebuddy-intl": {{ID: "glm-5.2", Name: "GLM-5.2"}, {ID: "glm-5.1", Name: "GLM-5.1"}, {ID: "glm-5.0", Name: "GLM-5.0"}, {ID: "glm-5.0-turbo", Name: "GLM-5.0-Turbo"}, {ID: "glm-5v-turbo", Name: "GLM-5v-Turbo"}, {ID: "glm-4.7", Name: "GLM-4.7"}, {ID: "minimax-m3", Name: "MiniMax-M3"}, {ID: "minimax-m2.7", Name: "MiniMax-M2.7"}, {ID: "kimi-k2.7", Name: "Kimi-K2.7-Code"}, {ID: "kimi-k2.6", Name: "Kimi-K2.6"}, {ID: "kimi-k2.5", Name: "Kimi-K2.5"}, {ID: "hy3-preview", Name: "Hy3 Preview"}, {ID: "deepseek-v4-pro", Name: "DeepSeek-V4-Pro"}, {ID: "deepseek-v4-flash", Name: "DeepSeek-V4-Flash"}, {ID: "deepseek-v3-2-volc", Name: "DeepSeek-V3.2"}},
	"codex":          {{ID: "gpt-5.6-sol", Name: "GPT 5.6 Sol"}, {ID: "gpt-5.6-sol-review", Name: "GPT 5.6 Sol Review"}, {ID: "gpt-5.6-terra", Name: "GPT 5.6 Terra"}, {ID: "gpt-5.6-terra-review", Name: "GPT 5.6 Terra Review"}, {ID: "gpt-5.6-luna", Name: "GPT 5.6 Luna"}, {ID: "gpt-5.6-luna-review", Name: "GPT 5.6 Luna Review"}, {ID: "gpt-5.5", Name: "GPT 5.5"}, {ID: "gpt-5.5-review", Name: "GPT 5.5 Review"}, {ID: "gpt-5.4", Name: "GPT 5.4"}, {ID: "gpt-5.4-review", Name: "GPT 5.4 Review"}, {ID: "gpt-5.4-mini", Name: "GPT 5.4 Mini"}, {ID: "gpt-5.4-mini-review", Name: "GPT 5.4 Mini Review"}, {ID: "gpt-5.3-codex-spark", Name: "GPT 5.3 Codex Spark"}, {ID: "gpt-5.3-codex-spark-review", Name: "GPT 5.3 Codex Spark Review"}},
	"cursor":         {{ID: "default", Name: "Auto (Server Picks)"}, {ID: "claude-4.5-opus-high-thinking", Name: "Claude 4.5 Opus High Thinking"}, {ID: "claude-4.5-opus-high", Name: "Claude 4.5 Opus High"}, {ID: "claude-4.5-sonnet-thinking", Name: "Claude 4.5 Sonnet Thinking"}, {ID: "claude-4.5-sonnet", Name: "Claude 4.5 Sonnet"}, {ID: "claude-4.5-haiku", Name: "Claude 4.5 Haiku"}, {ID: "claude-4.5-opus", Name: "Claude 4.5 Opus"}, {ID: "gpt-5.2-codex", Name: "GPT 5.2 Codex"}, {ID: "claude-4.6-opus-max", Name: "Claude 4.6 Opus Max"}, {ID: "claude-4.6-sonnet-medium-thinking", Name: "Claude 4.6 Sonnet Medium Thinking"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gpt-5.2", Name: "GPT 5.2"}, {ID: "gpt-5.3-codex", Name: "GPT 5.3 Codex"}},
	"deepseek":       {{ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-v4-pro-max", Name: "DeepSeek V4 Pro Max"}, {ID: "deepseek-v4-pro-none", Name: "DeepSeek V4 Pro No Thinking"}, {ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "deepseek-chat", Name: "DeepSeek V3.2 Chat"}, {ID: "deepseek-reasoner", Name: "DeepSeek V3.2 Reasoner"}},
	"gemini":         {{ID: "gemini-3.6-flash", Name: "Gemini 3.6 Flash"}, {ID: "gemini-3.5-flash-lite", Name: "Gemini 3.5 Flash Lite"}, {ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview"}, {ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}, {ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash Lite"}, {ID: "gemini-3.1-flash-image-preview", Name: "Gemini 3.1 Flash Image (Nano Banana 2)"}, {ID: "gemini-3-pro-image-preview", Name: "Gemini 3 Pro Image (Nano Banana Pro)"}, {ID: "gemini-2.5-flash-image", Name: "Gemini 2.5 Flash Image (Nano Banana)"}, {ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash"}},
	"github":         {{ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "gpt-5.2-codex", Name: "GPT-5.2 Codex"}, {ID: "gpt-5.3-codex", Name: "GPT-5.3 Codex"}, {ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "claude-haiku-4.5", Name: "Claude Haiku 4.5"}, {ID: "claude-opus-4.5", Name: "Claude Opus 4.5"}, {ID: "claude-sonnet-4.5", Name: "Claude Sonnet 4.5"}, {ID: "claude-sonnet-4.6", Name: "Claude Sonnet 4.6"}, {ID: "claude-opus-4.6", Name: "Claude Opus 4.6"}, {ID: "claude-opus-4.7", Name: "Claude Opus 4.7"}, {ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash"}, {ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro"}, {ID: "grok-code-fast-1", Name: "Grok Code Fast 1"}, {ID: "oswe-vscode-prime", Name: "Raptor Mini"}, {ID: "goldeneye-free-auto", Name: "GoldenEye"}},
	"glm":            {{ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "glm-5.1", Name: "GLM 5.1"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "glm-4.7", Name: "GLM 4.7"}, {ID: "glm-4.6v", Name: "GLM 4.6V (Vision)"}},
	"glm-cn":         {{ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "glm-5.1", Name: "GLM 5.1"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "glm-4.7", Name: "GLM-4.7"}, {ID: "glm-4.6", Name: "GLM-4.6"}, {ID: "glm-4.5-air", Name: "GLM-4.5-Air"}},
	"grok-cli":       {{ID: "grok-4.5", Name: "Grok 4.5"}, {ID: "grok-4.5-high", Name: "Grok 4.5 (High)"}, {ID: "grok-4.5-medium", Name: "Grok 4.5 (Medium)"}, {ID: "grok-4.5-low", Name: "Grok 4.5 (Low)"}},
	"groq":           {{ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B"}, {ID: "meta-llama/llama-4-maverick-17b-128e-instruct", Name: "Llama 4 Maverick"}, {ID: "qwen/qwen3-32b", Name: "Qwen3 32B"}, {ID: "openai/gpt-oss-120b", Name: "GPT-OSS 120B"}},
	"kimi":           {{ID: "kimi-k3", Name: "Kimi K3"}, {ID: "k3", Name: "Kimi K3 (Code)"}, {ID: "kimi-for-coding", Name: "Kimi for Coding"}, {ID: "kimi-for-coding-highspeed", Name: "Kimi for Coding Highspeed"}, {ID: "kimi-k2.7-code", Name: "Kimi K2.7 Code"}, {ID: "kimi-k2.7-code-highspeed", Name: "Kimi K2.7 Code Highspeed"}, {ID: "kimi-k2.6", Name: "Kimi K2.6"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "kimi-k2.5-thinking", Name: "Kimi K2.5 Thinking"}, {ID: "kimi-latest", Name: "Kimi Latest"}},
	"minimax":        {{ID: "MiniMax-M3", Name: "MiniMax M3"}, {ID: "MiniMax-M2.7", Name: "MiniMax M2.7"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "MiniMax-M2.1", Name: "MiniMax M2.1"}},
	"minimax-cn":     {{ID: "MiniMax-M3", Name: "MiniMax M3"}, {ID: "MiniMax-M2.7", Name: "MiniMax M2.7"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "MiniMax-M2.1", Name: "MiniMax M2.1"}},
	"nvidia":         {{ID: "minimaxai/minimax-m2.7", Name: "MiniMax M2.7"}, {ID: "minimaxai/minimax-m3", Name: "MiniMax M3"}, {ID: "z-ai/glm-5.2", Name: "GLM 5.2"}, {ID: "deepseek-ai/deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-ai/deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6"}, {ID: "nvidia/nemotron-3-ultra-550b-a55b", Name: "Nemotron 3 Ultra"}},
	"openai":         {{ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "gpt-5.4-nano", Name: "GPT-5.4 Nano"}, {ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "gpt-5.1", Name: "GPT-5.1"}, {ID: "gpt-5", Name: "GPT-5"}, {ID: "gpt-5-mini", Name: "GPT-5 Mini"}, {ID: "gpt-5-nano", Name: "GPT-5 Nano"}, {ID: "gpt-4o", Name: "GPT-4o"}, {ID: "gpt-4o-mini", Name: "GPT-4o Mini"}, {ID: "o3", Name: "O3"}, {ID: "o3-mini", Name: "O3 Mini"}, {ID: "o4-mini", Name: "O4 Mini"}, {ID: "o1", Name: "O1"}},
	"opencode":       {{ID: "big-pickle", Name: "Big Pickle (Free)"}, {ID: "mimo-v2.5-free", Name: "Mimo v2.5 (Free)"}, {ID: "ling-3.0-flash-fin-free", Name: "Ling 3.0 Flash (Free)"}, {ID: "deepseek-v4-flash-free", Name: "DeepSeek V4 Flash (Free)"}, {ID: "nemotron-3-ultra-free", Name: "Nemotron 3 Ultra (Free)"}, {ID: "nemotron-3.5-lightning-free", Name: "Nemotron 3.5 Lightning (Free)"}, {ID: "laguna-s-2.1-free", Name: "Laguna S 2.1 (Free)"}, {ID: "muse-spark-1.3-contributor-free", Name: "Muse Spark 1.3 (Free)"}, {ID: "muse-spark-1.2-contributor-free", Name: "Muse Spark 1.2 (Free)"}, {ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6"}, {ID: "claude-sonnet-4", Name: "Claude Sonnet 4"}, {ID: "claude-opus-4-6", Name: "Claude Opus 4.6"}, {ID: "gemini-3.7-flash", Name: "Gemini 3.7 Flash"}, {ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "kimi-k2.7-code", Name: "Kimi K2.7 Code"}, {ID: "minimax-m3", Name: "MiniMax M3"}, {ID: "qwen3.6-plus", Name: "Qwen 3.6 Plus"}},
	"openrouter":     {{ID: "openai/gpt-5.5", Name: "GPT-5.5"}, {ID: "openai/gpt-5.4", Name: "GPT-5.4"}, {ID: "anthropic/claude-sonnet-4-20250514", Name: "Claude Sonnet 4"}, {ID: "anthropic/claude-opus-4-20250514", Name: "Claude Opus 4"}, {ID: "google/gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "google/gemini-2.5-flash", Name: "Gemini 2.5 Flash"}, {ID: "deepseek/deepseek-chat", Name: "DeepSeek Chat"}, {ID: "deepseek/deepseek-reasoner", Name: "DeepSeek Reasoner"}},
	"qoder":          {{ID: "ultimate", Name: "Ultimate"}, {ID: "auto", Name: "Auto"}, {ID: "performance", Name: "Performance"}, {ID: "efficient", Name: "Efficient"}, {ID: "lite", Name: "Lite"}, {ID: "qmodel_38max", Name: "Qwen3.8-Max"}, {ID: "qmodel_latest", Name: "Qwen3.7-Max"}, {ID: "qmodel", Name: "Qwen3.7-Plus"}, {ID: "qfmodel", Name: "Qwen3.8-Flash"}, {ID: "kmodel_latest", Name: "Kimi-K3"}, {ID: "kmodel", Name: "Kimi-K2.7-Code"}, {ID: "gmodel", Name: "GLM-5.3"}, {ID: "gfmodel", Name: "GLM-5.3-Flash"}, {ID: "dmodel", Name: "DeepSeek-V4-Pro"}, {ID: "dfmodel", Name: "DeepSeek-V4-Flash"}, {ID: "mmodel", Name: "MiniMax-M3"}, {ID: "cmodel", Name: "Cantus"}},
	"tencent":        {{ID: "hunyuan-turbos-latest", Name: "Hunyuan TurboS Latest"}, {ID: "hunyuan-t1-latest", Name: "Hunyuan T1 Latest"}},
	"vertex":         {{ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview"}, {ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}},
	"xai":            {{ID: "grok-4", Name: "Grok 4"}, {ID: "grok-4-fast-reasoning", Name: "Grok 4 Fast Reasoning"}, {ID: "grok-code-fast-1", Name: "Grok Code Fast"}, {ID: "grok-3", Name: "Grok 3"}},
}

// GetRegistryModels returns the known registry models for a provider id (may be empty).
func GetRegistryModels(id string) []ModelRef {
	return RegistryModels[id]
}
