package provider

// registry_models.go is generated from 9router provider registry model lists.
// Source: decolua/9router open-sse/providers/registry/ @ 6fcd273
// Do not edit manually.

// ModelRef is a single model entry (id + display name) from the upstream registry.
type ModelRef struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// RegistryModels maps provider id -> its known model list from the 9router registry.
var RegistryModels = map[string][]ModelRef{
	"alicode":           {{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "qwen3-max-2026-01-23", Name: "Qwen3 Max"}, {ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"}, {ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "glm-4.7", Name: "GLM 4.7"}},
	"alicode-intl":      {{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"}, {ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "glm-4.7", Name: "GLM 4.7"}},
	"alims-intl":        {{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"}, {ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "glm-4.7", Name: "GLM 4.7"}},
	"anthropic":         {{ID: "claude-opus-5-20260701", Name: "Claude Opus 5"}, {ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"}, {ID: "claude-opus-4-20250514", Name: "Claude Opus 4"}, {ID: "claude-3-5-sonnet-20241022", Name: "Claude 3.5 Sonnet"}},
	"api-airforce":      {{ID: "anthropic/claude-3.7-sonnet", Name: "Claude 3.7 Sonnet (Free)"}, {ID: "moonshot/kimi-k2.6", Name: "Kimi K2.6 (Free)"}, {ID: "google/gemini-2.5-flash", Name: "Gemini 2.5 Flash (Free)"}},
	"antigravity":       {{ID: "gemini-3-flash-agent", Name: "Gemini 3.5 Flash (High)"}, {ID: "gemini-3.5-flash-low", Name: "Gemini 3.5 Flash (Medium)"}, {ID: "gemini-3.5-flash-extra-low", Name: "Gemini 3.5 Flash (Low)"}, {ID: "gemini-pro-agent", Name: "Gemini 3.1 Pro (High)"}, {ID: "gemini-3.1-pro-low", Name: "Gemini 3.1 Pro (Low)"}, {ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6 (Thinking)"}, {ID: "claude-opus-4-6-thinking", Name: "Claude Opus 4.6 (Thinking)"}, {ID: "gpt-oss-120b-medium", Name: "GPT-OSS 120B (Medium)"}, {ID: "gemini-3-flash", Name: "Gemini 3 Flash"}, {ID: "gemini-3.1-flash-image", Name: "Gemini 3.1 Flash (Image)"}},
	"baidu":             {{ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "glm-5.1", Name: "GLM 5.1"}, {ID: "kimi-k2.6", Name: "Kimi K2.6"}, {ID: "qwen3.5-397b-a17b", Name: "Qwen 3.5 397B A17B"}, {ID: "qwen3.5-27b", Name: "Qwen 3.5 27B"}},
	"bazaarlink":        {{ID: "auto:free", Name: "Auto Free (Zero Cost)"}, {ID: "claude-opus-4.7", Name: "Claude Opus 4.7"}, {ID: "claude-sonnet-4.6", Name: "Claude Sonnet 4.6"}, {ID: "gpt-5.5", Name: "GPT-5.5"}, {ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "grok-4.3", Name: "Grok 4.3"}, {ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro"}, {ID: "kimi-k2.6", Name: "Kimi K2.6"}, {ID: "mimo-v2.5-pro", Name: "MiMo-V2.5-Pro"}, {ID: "minimax-m3", Name: "MiniMax M3"}},
	"assemblyai":        {{ID: "universal-3-pro", Name: "Universal 3 Pro"}, {ID: "universal-2", Name: "Universal 2"}, {ID: "best", Name: "Best (Nano + Universal)"}, {ID: "nano", Name: "Nano (Fast)"}},
	"black-forest-labs": {{ID: "flux-pro-1.1", Name: "FLUX Pro 1.1"}, {ID: "flux-pro-1.1-ultra", Name: "FLUX Pro 1.1 Ultra"}, {ID: "flux-pro", Name: "FLUX Pro"}, {ID: "flux-dev", Name: "FLUX Dev"}, {ID: "flux-kontext-pro", Name: "FLUX Kontext Pro (Edit)"}, {ID: "flux-kontext-max", Name: "FLUX Kontext Max (Edit)"}},
	"blackbox":          {{ID: "claude-fable-5", Name: "Claude Fable 5"}, {ID: "claude-opus-4.8", Name: "Claude Opus 4.8"}, {ID: "claude-sonnet-4.6", Name: "Claude Sonnet 4.6"}, {ID: "gpt-5.5", Name: "GPT-5.5"}, {ID: "gpt-5.4-pro", Name: "GPT-5.4 Pro"}, {ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.3-codex", Name: "GPT-5.3 Codex"}, {ID: "gpt-5.4-nano", Name: "GPT-5.4 Nano"}, {ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "grok-4.3", Name: "Grok 4.3"}},
	"byteplus":          {{ID: "seed-2-0-pro-260328", Name: "Seed 2.0 Pro"}, {ID: "seed-2-0-code-preview-260328", Name: "Seed 2.0 Code Preview"}, {ID: "seed-2-0-mini-260215", Name: "Seed 2.0 Mini"}, {ID: "seed-2-0-lite-260228", Name: "Seed 2.0 Lite"}, {ID: "kimi-k2-thinking-251104", Name: "Kimi K2 Thinking"}, {ID: "glm-4-7-251222", Name: "GLM 4.7"}, {ID: "gpt-oss-120b-250805", Name: "GPT-OSS-120B"}},
	"cerebras":          {{ID: "gpt-oss-120b", Name: "GPT OSS 120B"}, {ID: "zai-glm-4.7", Name: "ZAI GLM 4.7"}, {ID: "llama-3.3-70b", Name: "Llama 3.3 70B"}, {ID: "llama-4-scout-17b-16e-instruct", Name: "Llama 4 Scout"}, {ID: "qwen-3-235b-a22b-instruct-2507", Name: "Qwen3 235B A22B"}, {ID: "qwen-3-32b", Name: "Qwen3 32B"}},
	"claude":            {{ID: "claude-fable-5", Name: "Claude Fable 5"}, {ID: "claude-sonnet-5", Name: "Claude Sonnet 5"}, {ID: "claude-opus-4-8", Name: "Claude Opus 4.8"}, {ID: "claude-opus-4-7", Name: "Claude Opus 4.7"}, {ID: "claude-haiku-4-5-20251001", Name: "Claude 4.5 Haiku"}},
	"cline":             {{ID: "anthropic/claude-opus-4.7", Name: "Claude Opus 4.7"}, {ID: "anthropic/claude-sonnet-4.6", Name: "Claude Sonnet 4.6"}, {ID: "anthropic/claude-opus-4.6", Name: "Claude Opus 4.6"}, {ID: "openai/gpt-5.3-codex", Name: "GPT-5.3 Codex"}, {ID: "openai/gpt-5.4", Name: "GPT-5.4"}, {ID: "google/gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview"}, {ID: "google/gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview"}, {ID: "kwaipilot/kat-coder-pro", Name: "KAT Coder Pro"}},
	"clinepass":         {{ID: "cline-pass/glm-5.2", Name: "GLM-5.2 (ClinePass)"}, {ID: "cline-pass/kimi-k2.7-code", Name: "Kimi K2.7 Code (ClinePass)"}, {ID: "cline-pass/kimi-k2.6", Name: "Kimi K2.6 (ClinePass)"}, {ID: "cline-pass/deepseek-v4-pro", Name: "DeepSeek V4 Pro (ClinePass)"}, {ID: "cline-pass/deepseek-v4-flash", Name: "DeepSeek V4 Flash (ClinePass)"}, {ID: "cline-pass/mimo-v2.5", Name: "MiMo-V2.5 (ClinePass)"}, {ID: "cline-pass/mimo-v2.5-pro", Name: "MiMo-V2.5-Pro (ClinePass)"}, {ID: "cline-pass/minimax-m3", Name: "MiniMax M3 (ClinePass)"}, {ID: "cline-pass/qwen3.7-max", Name: "Qwen3.7 Max (ClinePass)"}, {ID: "cline-pass/qwen3.7-plus", Name: "Qwen3.7 Plus (ClinePass)"}},
	"cloudflare-ai":     {{ID: "@cf/meta/llama-3.2-1b-instruct", Name: "Llama 3.2 1B Instruct"}, {ID: "@cf/meta/llama-3.2-3b-instruct", Name: "Llama 3.2 3B Instruct"}, {ID: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", Name: "Llama 3.1 8B Instruct FP8 Fast"}, {ID: "@cf/meta/llama-3.1-8b-instruct-awq", Name: "Llama 3.1 8B Instruct AWQ"}, {ID: "@cf/mistralai/mistral-small-3.1-24b-instruct", Name: "Mistral Small 3.1 24B Instruct"}, {ID: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", Name: "Llama 3.1 70B Instruct FP8 Fast"}, {ID: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", Name: "Llama 3.3 70B Instruct FP8 Fast"}, {ID: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", Name: "DeepSeek R1 Distill Qwen 32B"}, {ID: "@cf/moonshotai/kimi-k2.5", Name: "Kimi K2.5"}, {ID: "@cf/moonshotai/kimi-k2.6", Name: "Kimi K2.6"}, {ID: "@cf/zai-org/glm-4.7-flash", Name: "GLM 4.7 Flash"}, {ID: "@cf/qwen/qwq-32b", Name: "QwQ 32B"}, {ID: "@cf/qwen/qwen2.5-coder-32b-instruct", Name: "Qwen 2.5 Coder 32B Instruct"}, {ID: "@cf/black-forest-labs/flux-2-klein-9b", Name: "FLUX.2 Klein 9B"}, {ID: "@cf/black-forest-labs/flux-2-klein-4b", Name: "FLUX.2 Klein 4B"}, {ID: "@cf/black-forest-labs/flux-2-dev", Name: "FLUX.2 Dev"}, {ID: "@cf/leonardo/lucid-origin", Name: "Lucid Origin"}, {ID: "@cf/leonardo/phoenix-1.0", Name: "Phoenix 1.0"}, {ID: "@cf/black-forest-labs/flux-1-schnell", Name: "FLUX.1 Schnell"}, {ID: "@cf/bytedance/stable-diffusion-xl-lightning", Name: "SDXL Lightning"}, {ID: "@cf/lykon/dreamshaper-8-lcm", Name: "DreamShaper 8 LCM"}, {ID: "@cf/runwayml/stable-diffusion-v1-5-img2img", Name: "Stable Diffusion v1.5 Img2Img"}, {ID: "@cf/runwayml/stable-diffusion-v1-5-inpainting", Name: "Stable Diffusion v1.5 Inpainting"}, {ID: "@cf/stabilityai/stable-diffusion-xl-base-1.0", Name: "SDXL Base 1.0"}},
	"codebuddy-cn":      {{ID: "glm-5.2", Name: "GLM-5.2"}, {ID: "glm-5.1", Name: "GLM-5.1"}, {ID: "glm-5.0", Name: "GLM-5.0"}, {ID: "glm-5.0-turbo", Name: "GLM-5.0-Turbo"}, {ID: "glm-5v-turbo", Name: "GLM-5v-Turbo"}, {ID: "glm-4.7", Name: "GLM-4.7"}, {ID: "minimax-m3", Name: "MiniMax-M3"}, {ID: "minimax-m2.7", Name: "MiniMax-M2.7"}, {ID: "kimi-k2.7", Name: "Kimi-K2.7-Code"}, {ID: "kimi-k2.6", Name: "Kimi-K2.6"}, {ID: "kimi-k2.5", Name: "Kimi-K2.5"}, {ID: "hy3-preview", Name: "Hy3 Preview"}, {ID: "deepseek-v4-pro", Name: "DeepSeek-V4-Pro"}, {ID: "deepseek-v4-flash", Name: "DeepSeek-V4-Flash"}, {ID: "deepseek-v3-2-volc", Name: "DeepSeek-V3.2"}},
	"codex":             {{ID: "gpt-5.6-sol", Name: "GPT 5.6 Sol"}, {ID: "gpt-5.6-sol-review", Name: "GPT 5.6 Sol Review"}, {ID: "gpt-5.6-terra", Name: "GPT 5.6 Terra"}, {ID: "gpt-5.6-terra-review", Name: "GPT 5.6 Terra Review"}, {ID: "gpt-5.6-luna", Name: "GPT 5.6 Luna"}, {ID: "gpt-5.6-luna-review", Name: "GPT 5.6 Luna Review"}, {ID: "gpt-5.5", Name: "GPT 5.5"}, {ID: "gpt-5.5-review", Name: "GPT 5.5 Review"}, {ID: "gpt-5.4", Name: "GPT 5.4"}, {ID: "gpt-5.4-review", Name: "GPT 5.4 Review"}, {ID: "gpt-5.4-mini", Name: "GPT 5.4 Mini"}, {ID: "gpt-5.4-mini-review", Name: "GPT 5.4 Mini Review"}, {ID: "gpt-5.3-codex-spark", Name: "GPT 5.3 Codex Spark"}, {ID: "gpt-5.3-codex-spark-review", Name: "GPT 5.3 Codex Spark Review"}, {ID: "gpt-5.5-image", Name: "GPT 5.5 Image"}, {ID: "gpt-5.4-image", Name: "GPT 5.4 Image"}, {ID: "gpt-5.3-image", Name: "GPT 5.3 Image"}},
	"cohere":            {{ID: "command-r-plus-08-2024", Name: "Command R+ (Aug 2024)"}, {ID: "command-r-08-2024", Name: "Command R (Aug 2024)"}, {ID: "command-a-03-2025", Name: "Command A (Mar 2025)"}},
	"comfyui":           {{ID: "flux-dev", Name: "FLUX Dev"}, {ID: "sdxl", Name: "SDXL"}},
	"commandcode":       {{ID: "deepseek/deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek/deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "moonshotai/Kimi-K2.6", Name: "Kimi K2.6"}, {ID: "moonshotai/Kimi-K2.5", Name: "Kimi K2.5"}, {ID: "zai-org/GLM-5.1", Name: "GLM 5.1"}, {ID: "zai-org/GLM-5", Name: "GLM 5"}, {ID: "MiniMaxAI/MiniMax-M2.7", Name: "MiniMax M2.7"}, {ID: "MiniMaxAI/MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "Qwen/Qwen3.6-Max-Preview", Name: "Qwen 3.6 Max Preview"}, {ID: "Qwen/Qwen3.6-Plus", Name: "Qwen 3.6 Plus"}, {ID: "stepfun/Step-3.5-Flash", Name: "Step 3.5 Flash"}},
	"cursor":            {{ID: "default", Name: "Auto (Server Picks)"}, {ID: "claude-4.5-opus-high-thinking", Name: "Claude 4.5 Opus High Thinking"}, {ID: "claude-4.5-opus-high", Name: "Claude 4.5 Opus High"}, {ID: "claude-4.5-sonnet-thinking", Name: "Claude 4.5 Sonnet Thinking"}, {ID: "claude-4.5-sonnet", Name: "Claude 4.5 Sonnet"}, {ID: "claude-4.5-haiku", Name: "Claude 4.5 Haiku"}, {ID: "claude-4.5-opus", Name: "Claude 4.5 Opus"}, {ID: "gpt-5.2-codex", Name: "GPT 5.2 Codex"}, {ID: "claude-4.6-opus-max", Name: "Claude 4.6 Opus Max"}, {ID: "claude-4.6-sonnet-medium-thinking", Name: "Claude 4.6 Sonnet Medium Thinking"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gpt-5.2", Name: "GPT 5.2"}, {ID: "gpt-5.3-codex", Name: "GPT 5.3 Codex"}},
	"deepgram":          {{ID: "nova-3", Name: "Nova 3"}, {ID: "nova-2", Name: "Nova 2"}, {ID: "whisper-large", Name: "Whisper Large"}, {ID: "nova", Name: "Nova"}},
	"deepseek":          {{ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-v4-pro-max", Name: "DeepSeek V4 Pro Max"}, {ID: "deepseek-v4-pro-none", Name: "DeepSeek V4 Pro No Thinking"}, {ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "deepseek-chat", Name: "DeepSeek V3.2 Chat"}, {ID: "deepseek-reasoner", Name: "DeepSeek V3.2 Reasoner"}},
	"fal-ai":            {{ID: "fal-ai/flux/schnell", Name: "FLUX Schnell"}, {ID: "fal-ai/flux/dev", Name: "FLUX Dev"}, {ID: "fal-ai/flux-pro/v1.1", Name: "FLUX Pro v1.1"}, {ID: "fal-ai/flux-pro/v1.1-ultra", Name: "FLUX Pro v1.1 Ultra"}, {ID: "fal-ai/recraft-v3", Name: "Recraft V3"}, {ID: "fal-ai/ideogram/v2", Name: "Ideogram V2"}, {ID: "fal-ai/stable-diffusion-v35-large", Name: "SD 3.5 Large"}},
	"featherless":       {{ID: "deepseek-ai/DeepSeek-V4-Pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-ai/DeepSeek-V4-Flash", Name: "DeepSeek V4 Flash"}, {ID: "zai-org/GLM-5.2", Name: "GLM 5.2"}, {ID: "zai-org/GLM-5.1", Name: "GLM 5.1"}, {ID: "moonshotai/Kimi-K2.7-Code", Name: "Kimi K2.7 Code"}, {ID: "moonshotai/Kimi-K2.6", Name: "Kimi K2.6"}, {ID: "moonshotai/Kimi-K2.5", Name: "Kimi K2.5"}},
	"fireworks":         {{ID: "accounts/fireworks/models/deepseek-v3p1", Name: "DeepSeek V3.1"}, {ID: "accounts/fireworks/models/llama-v3p3-70b-instruct", Name: "Llama 3.3 70B"}, {ID: "accounts/fireworks/models/qwen3-235b-a22b", Name: "Qwen3 235B"}, {ID: "nomic-ai/nomic-embed-text-v1.5", Name: "Nomic Embed Text v1.5"}},
	"gemini":            {{ID: "gemini-3.6-flash", Name: "Gemini 3.6 Flash"}, {ID: "gemini-3.5-flash-lite", Name: "Gemini 3.5 Flash Lite"}, {ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview"}, {ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}, {ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash Lite"}, {ID: "gemma-4-31b-it", Name: "Gemma 4 31B IT"}, {ID: "gemini-embedding-2-preview", Name: "Gemini Embedding 2 Preview"}, {ID: "gemini-embedding-001", Name: "Gemini Embedding 001"}, {ID: "text-embedding-005", Name: "Text Embedding 005"}, {ID: "text-embedding-004", Name: "Text Embedding 004 (Legacy)"}, {ID: "gemini-3.1-flash-image-preview", Name: "Gemini 3.1 Flash Image (Nano Banana 2)"}, {ID: "gemini-3-pro-image-preview", Name: "Gemini 3 Pro Image (Nano Banana Pro)"}, {ID: "gemini-2.5-flash-image", Name: "Gemini 2.5 Flash Image (Nano Banana)"}, {ID: "gemini-2.0-flash", Name: "Gemini 2.0 Flash"}, {ID: "gemini-3.1-flash-tts-preview", Name: "Gemini 3.1 Flash TTS"}, {ID: "gemini-2.5-flash-preview-tts", Name: "Gemini 2.5 Flash TTS"}, {ID: "gemini-2.5-pro-preview-tts", Name: "Gemini 2.5 Pro TTS"}, {ID: "embedding-001", Name: "Embedding 001"}},
	"gemini-cli":        {{ID: "gemini-3.6-flash", Name: "Gemini 3.6 Flash"}, {ID: "gemini-3.5-flash-lite", Name: "Gemini 3.5 Flash Lite"}, {ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview"}, {ID: "gemini-3-pro-preview", Name: "Gemini 3 Pro Preview"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview"}, {ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}, {ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash Lite"}},
	"github":            {{ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "gpt-5.2-codex", Name: "GPT-5.2 Codex"}, {ID: "gpt-5.3-codex", Name: "GPT-5.3 Codex"}, {ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "claude-haiku-4.5", Name: "Claude Haiku 4.5"}, {ID: "claude-opus-4.5", Name: "Claude Opus 4.5"}, {ID: "claude-sonnet-4.5", Name: "Claude Sonnet 4.5"}, {ID: "claude-sonnet-4.6", Name: "Claude Sonnet 4.6"}, {ID: "claude-opus-4.6", Name: "Claude Opus 4.6"}, {ID: "claude-opus-4.7", Name: "Claude Opus 4.7"}, {ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash"}, {ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro"}, {ID: "grok-code-fast-1", Name: "Grok Code Fast 1"}, {ID: "oswe-vscode-prime", Name: "Raptor Mini"}, {ID: "goldeneye-free-auto", Name: "GoldenEye"}, {ID: "text-embedding-3-small", Name: "Text Embedding 3 Small (GitHub)"}, {ID: "text-embedding-3-large", Name: "Text Embedding 3 Large (GitHub)"}},
	"glm":               {{ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "glm-5.1", Name: "GLM 5.1"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "glm-4.7", Name: "GLM 4.7"}, {ID: "glm-4.6v", Name: "GLM 4.6V (Vision)"}},
	"glm-cn":            {{ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "glm-5.1", Name: "GLM 5.1"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "glm-4.7", Name: "GLM-4.7"}, {ID: "glm-4.6", Name: "GLM-4.6"}, {ID: "glm-4.5-air", Name: "GLM-4.5-Air"}},
	"grok-cli":          {{ID: "grok-4.5", Name: "Grok 4.5"}, {ID: "grok-4.5-high", Name: "Grok 4.5 (High)"}, {ID: "grok-4.5-medium", Name: "Grok 4.5 (Medium)"}, {ID: "grok-4.5-low", Name: "Grok 4.5 (Low)"}},
	"grok-web":          {{ID: "grok-3", Name: "Grok 3"}, {ID: "grok-3-mini", Name: "Grok 3 Mini (Thinking)"}, {ID: "grok-3-thinking", Name: "Grok 3 Thinking"}, {ID: "grok-4", Name: "Grok 4"}, {ID: "grok-4-mini", Name: "Grok 4 Mini (Thinking)"}, {ID: "grok-4-thinking", Name: "Grok 4 Thinking"}, {ID: "grok-4-heavy", Name: "Grok 4 Heavy (SuperGrok)"}, {ID: "grok-4.1-mini", Name: "Grok 4.1 Mini (Thinking)"}, {ID: "grok-4.1-fast", Name: "Grok 4.1 Fast"}, {ID: "grok-4.1-expert", Name: "Grok 4.1 Expert"}, {ID: "grok-4.1-thinking", Name: "Grok 4.1 Thinking"}, {ID: "grok-4.2", Name: "Grok 4.2 (4.20 Beta)"}},
	"groq":              {{ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B"}, {ID: "meta-llama/llama-4-maverick-17b-128e-instruct", Name: "Llama 4 Maverick"}, {ID: "qwen/qwen3-32b", Name: "Qwen3 32B"}, {ID: "openai/gpt-oss-120b", Name: "GPT-OSS 120B"}, {ID: "whisper-large-v3", Name: "Whisper Large v3"}, {ID: "whisper-large-v3-turbo", Name: "Whisper Large v3 Turbo"}, {ID: "distil-whisper-large-v3-en", Name: "Distil Whisper Large v3 EN"}},
	"huggingface":       {{ID: "black-forest-labs/FLUX.1-schnell", Name: "FLUX.1 Schnell"}, {ID: "stabilityai/stable-diffusion-xl-base-1.0", Name: "SDXL Base 1.0"}, {ID: "openai/whisper-large-v3", Name: "Whisper Large v3 (HF)"}, {ID: "openai/whisper-small", Name: "Whisper Small (HF)"}},
	"hyperbolic":        {{ID: "Qwen/QwQ-32B", Name: "QwQ 32B"}, {ID: "deepseek-ai/DeepSeek-R1", Name: "DeepSeek R1"}, {ID: "deepseek-ai/DeepSeek-V3", Name: "DeepSeek V3"}, {ID: "meta-llama/Llama-3.3-70B-Instruct", Name: "Llama 3.3 70B"}, {ID: "meta-llama/Llama-3.2-3B-Instruct", Name: "Llama 3.2 3B"}, {ID: "Qwen/Qwen2.5-72B-Instruct", Name: "Qwen 2.5 72B"}, {ID: "Qwen/Qwen2.5-Coder-32B-Instruct", Name: "Qwen 2.5 Coder 32B"}, {ID: "NousResearch/Hermes-3-Llama-3.1-70B", Name: "Hermes 3 70B"}},
	"iflow":             {{ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "qwen3-max", Name: "Qwen3 Max"}, {ID: "qwen3-vl-plus", Name: "Qwen3 VL Plus"}, {ID: "qwen3-max-preview", Name: "Qwen3 Max Preview"}, {ID: "qwen3-235b", Name: "Qwen3 235B A22B"}, {ID: "qwen3-235b-a22b-instruct", Name: "Qwen3 235B A22B Instruct"}, {ID: "qwen3-235b-a22b-thinking-2507", Name: "Qwen3 235B A22B Thinking"}, {ID: "qwen3-32b", Name: "Qwen3 32B"}, {ID: "kimi-k2", Name: "Kimi K2"}, {ID: "deepseek-v3.2", Name: "DeepSeek V3.2 Exp"}, {ID: "deepseek-v3.1", Name: "DeepSeek V3.1 Terminus"}, {ID: "deepseek-v3", Name: "DeepSeek V3 671B"}, {ID: "deepseek-r1", Name: "DeepSeek R1"}, {ID: "glm-4.7", Name: "GLM 4.7"}, {ID: "iflow-rome-30ba3b", Name: "iFlow ROME"}},
	"kilo-gateway":      {{ID: "kilo-auto/free", Name: "Kilo Auto Free"}, {ID: "nvidia/nemotron-3-super-120b-a12b:free", Name: "Nemotron 3 Super 120B (Free)"}, {ID: "nvidia/nemotron-3-ultra-550b-a55b:free", Name: "Nemotron 3 Ultra 550B (Free)"}, {ID: "kwaipilot/kat-coder-pro-v2.5:free", Name: "Kat Coder Pro v2.5 (Free)"}, {ID: "kilo-auto/frontier", Name: "Kilo Auto Frontier"}, {ID: "kilo-auto/balanced", Name: "Kilo Auto Balanced"}},
	"kilocode":          {{ID: "anthropic/claude-sonnet-4-20250514", Name: "Claude Sonnet 4"}, {ID: "anthropic/claude-opus-4-20250514", Name: "Claude Opus 4"}, {ID: "google/gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "google/gemini-2.5-flash", Name: "Gemini 2.5 Flash"}, {ID: "openai/gpt-4.1", Name: "GPT-4.1"}, {ID: "openai/o3", Name: "o3"}, {ID: "deepseek/deepseek-chat", Name: "DeepSeek Chat"}, {ID: "deepseek/deepseek-reasoner", Name: "DeepSeek Reasoner"}},
	"kimchi":            {{ID: "minimax-m3", Name: "MiniMax-M3"}, {ID: "kimi-k2.7", Name: "Kimi-K2.7"}, {ID: "kimi-k2.6", Name: "Kimi-K2.6"}, {ID: "kimi-k2.5", Name: "Kimi-K2.5"}, {ID: "nemotron-3-ultra-fp4", Name: "Nemotron 3 Ultra FP4"}, {ID: "minimax-m2.7", Name: "MiniMax-M2.7"}, {ID: "claude-opus-4-6", Name: "Claude Opus 4.6"}, {ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6"}},
	"kimi":              {{ID: "kimi-k3", Name: "Kimi K3"}, {ID: "k3", Name: "Kimi K3 (Code)"}, {ID: "kimi-for-coding", Name: "Kimi for Coding"}, {ID: "kimi-for-coding-highspeed", Name: "Kimi for Coding Highspeed"}, {ID: "kimi-k2.7-code", Name: "Kimi K2.7 Code"}, {ID: "kimi-k2.7-code-highspeed", Name: "Kimi K2.7 Code Highspeed"}, {ID: "kimi-k2.6", Name: "Kimi K2.6"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "kimi-k2.5-thinking", Name: "Kimi K2.5 Thinking"}, {ID: "kimi-latest", Name: "Kimi Latest"}},
	"kiro":              {{ID: "claude-opus-5", Name: "Claude Opus 5"}, {ID: "claude-opus-5-thinking", Name: "Claude Opus 5 (Thinking)"}, {ID: "claude-opus-5-agentic", Name: "Claude Opus 5 (Agentic)"}, {ID: "claude-opus-5-thinking-agentic", Name: "Claude Opus 5 (Thinking + Agentic)"}, {ID: "claude-opus-4.8", Name: "Claude Opus 4.8"}, {ID: "claude-opus-4.8-thinking", Name: "Claude Opus 4.8 (Thinking)"}, {ID: "claude-opus-4.8-agentic", Name: "Claude Opus 4.8 (Agentic)"}, {ID: "claude-opus-4.8-thinking-agentic", Name: "Claude Opus 4.8 (Thinking + Agentic)"}, {ID: "claude-opus-4.7", Name: "Claude Opus 4.7"}, {ID: "claude-opus-4.7-thinking", Name: "Claude Opus 4.7 (Thinking)"}, {ID: "claude-opus-4.7-agentic", Name: "Claude Opus 4.7 (Agentic)"}, {ID: "claude-opus-4.7-thinking-agentic", Name: "Claude Opus 4.7 (Thinking + Agentic)"}, {ID: "claude-opus-4.5", Name: "Claude Opus 4.5"}, {ID: "claude-opus-4.5-thinking", Name: "Claude Opus 4.5 (Thinking)"}, {ID: "claude-opus-4.5-agentic", Name: "Claude Opus 4.5 (Agentic)"}, {ID: "claude-opus-4.5-thinking-agentic", Name: "Claude Opus 4.5 (Thinking + Agentic)"}, {ID: "claude-sonnet-5", Name: "Claude Sonnet 5"}, {ID: "claude-sonnet-4.5", Name: "Claude Sonnet 4.5"}, {ID: "claude-haiku-4.5", Name: "Claude Haiku 4.5"}, {ID: "deepseek-3.2", Name: "DeepSeek 3.2"}, {ID: "qwen3-coder-next", Name: "Qwen3 Coder Next"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "gpt-5.6-sol", Name: "GPT 5.6 Sol"}, {ID: "gpt-5.6-terra", Name: "GPT 5.6 Terra"}, {ID: "gpt-5.6-luna", Name: "GPT 5.6 Luna"}, {ID: "claude-sonnet-5-thinking", Name: "Claude Sonnet 5 (Thinking)"}, {ID: "claude-sonnet-4.5-thinking", Name: "Claude Sonnet 4.5 (Thinking)"}, {ID: "claude-haiku-4.5-thinking", Name: "Claude Haiku 4.5 (Thinking)"}, {ID: "gpt-5.6-sol-thinking", Name: "GPT 5.6 Sol (Thinking)"}, {ID: "gpt-5.6-terra-thinking", Name: "GPT 5.6 Terra (Thinking)"}, {ID: "gpt-5.6-luna-thinking", Name: "GPT 5.6 Luna (Thinking)"}, {ID: "claude-sonnet-5-agentic", Name: "Claude Sonnet 5 (Agentic)"}, {ID: "claude-sonnet-4.5-agentic", Name: "Claude Sonnet 4.5 (Agentic)"}, {ID: "claude-haiku-4.5-agentic", Name: "Claude Haiku 4.5 (Agentic)"}, {ID: "gpt-5.6-sol-agentic", Name: "GPT 5.6 Sol (Agentic)"}, {ID: "gpt-5.6-terra-agentic", Name: "GPT 5.6 Terra (Agentic)"}, {ID: "gpt-5.6-luna-agentic", Name: "GPT 5.6 Luna (Agentic)"}, {ID: "claude-sonnet-5-thinking-agentic", Name: "Claude Sonnet 5 (Thinking + Agentic)"}, {ID: "claude-sonnet-4.5-thinking-agentic", Name: "Claude Sonnet 4.5 (Thinking + Agentic)"}, {ID: "claude-haiku-4.5-thinking-agentic", Name: "Claude Haiku 4.5 (Thinking + Agentic)"}, {ID: "gpt-5.6-sol-thinking-agentic", Name: "GPT 5.6 Sol (Thinking + Agentic)"}, {ID: "gpt-5.6-terra-thinking-agentic", Name: "GPT 5.6 Terra (Thinking + Agentic)"}, {ID: "gpt-5.6-luna-thinking-agentic", Name: "GPT 5.6 Luna (Thinking + Agentic)"}},
	"llm7":              {{ID: "gpt-5.5", Name: "GPT-5.5 (LLM7)"}, {ID: "claude-opus-5", Name: "Claude Opus 5 (LLM7)"}, {ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash (LLM7)"}, {ID: "grok-4.5", Name: "Grok 4.5 (LLM7)"}, {ID: "kimi-k3", Name: "Kimi K3 (LLM7)"}},
	"mimo-free":         {{ID: "mimo-auto", Name: "MiMo Auto"}},
	"minimax":           {{ID: "MiniMax-M3", Name: "MiniMax M3"}, {ID: "MiniMax-M2.7", Name: "MiniMax M2.7"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "MiniMax-M2.1", Name: "MiniMax M2.1"}, {ID: "minimax-image-01", Name: "MiniMax Image 01"}, {ID: "speech-2.8-hd", Name: "Speech 2.8 HD"}, {ID: "speech-2.8-turbo", Name: "Speech 2.8 Turbo"}, {ID: "speech-2.6-hd", Name: "Speech 2.6 HD"}, {ID: "speech-2.6-turbo", Name: "Speech 2.6 Turbo"}, {ID: "speech-02-hd", Name: "Speech 02 HD"}, {ID: "speech-02-turbo", Name: "Speech 02 Turbo"}, {ID: "speech-01-hd", Name: "Speech 01 HD"}, {ID: "speech-01-turbo", Name: "Speech 01 Turbo"}},
	"minimax-cn":        {{ID: "MiniMax-M3", Name: "MiniMax M3"}, {ID: "MiniMax-M2.7", Name: "MiniMax M2.7"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "MiniMax-M2.1", Name: "MiniMax M2.1"}, {ID: "speech-2.8-hd", Name: "Speech 2.8 HD"}, {ID: "speech-2.8-turbo", Name: "Speech 2.8 Turbo"}, {ID: "speech-2.6-hd", Name: "Speech 2.6 HD"}, {ID: "speech-2.6-turbo", Name: "Speech 2.6 Turbo"}, {ID: "speech-02-hd", Name: "Speech 02 HD"}, {ID: "speech-02-turbo", Name: "Speech 02 Turbo"}, {ID: "speech-01-hd", Name: "Speech 01 HD"}, {ID: "speech-01-turbo", Name: "Speech 01 Turbo"}},
	"mistral":           {{ID: "mistral-large-latest", Name: "Mistral Large 3"}, {ID: "codestral-latest", Name: "Codestral"}, {ID: "mistral-medium-latest", Name: "Mistral Medium 3"}, {ID: "mistral-embed", Name: "Mistral Embed"}},
	"mmf":               {{ID: "mimo-auto", Name: "MiMo Auto"}},
	"morph":             {{ID: "morph-v3-large", Name: "Morph v3 Large"}, {ID: "morph-v3-fast", Name: "Morph v3 Fast"}, {ID: "morph-qwen35-397b", Name: "Qwen 3.5 397B (Morph)"}, {ID: "morph-minimax27-230b", Name: "MiniMax M2.7 (Morph)"}, {ID: "morph-qwen36-27b", Name: "Qwen 3.6 27B (Morph)"}, {ID: "morph-dsv4flash", Name: "DeepSeek V4 Flash (Morph)"}},
	"nanobanana":        {{ID: "nanobanana-flash", Name: "NanoBanana Flash"}, {ID: "nanobanana-pro", Name: "NanoBanana Pro"}},
	"nebius":            {{ID: "meta-llama/Llama-3.3-70B-Instruct", Name: "Llama 3.3 70B Instruct"}, {ID: "Qwen/Qwen3-Embedding-8B", Name: "Qwen3 Embedding 8B"}},
	"nvidia":            {{ID: "minimaxai/minimax-m2.7", Name: "MiniMax M2.7"}, {ID: "minimaxai/minimax-m3", Name: "MiniMax M3"}, {ID: "z-ai/glm-5.2", Name: "GLM 5.2"}, {ID: "deepseek-ai/deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-ai/deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6"}, {ID: "nvidia/nemotron-3-ultra-550b-a55b", Name: "Nemotron 3 Ultra"}, {ID: "nvidia/nv-embedqa-e5-v5", Name: "NV EmbedQA E5 v5"}, {ID: "nvidia/parakeet-ctc-1.1b-asr", Name: "Parakeet CTC 1.1B"}, {ID: "fastpitch", Name: "FastPitch"}, {ID: "tacotron2", Name: "Tacotron2"}},
	"ollama":            {{ID: "gpt-oss:120b", Name: "GPT OSS 120B"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "glm-5", Name: "GLM 5"}, {ID: "minimax-m2.5", Name: "MiniMax M2.5"}, {ID: "glm-4.7-flash", Name: "GLM 4.7 Flash"}, {ID: "qwen3.5", Name: "Qwen3.5"}, {ID: "minimax-m3", Name: "MiniMax M3"}},
	"openai":            {{ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "gpt-5.4-nano", Name: "GPT-5.4 Nano"}, {ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "gpt-5.1", Name: "GPT-5.1"}, {ID: "gpt-5", Name: "GPT-5"}, {ID: "gpt-5-mini", Name: "GPT-5 Mini"}, {ID: "gpt-5-nano", Name: "GPT-5 Nano"}, {ID: "gpt-4o", Name: "GPT-4o"}, {ID: "gpt-4o-mini", Name: "GPT-4o Mini"}, {ID: "gpt-4-turbo", Name: "GPT-4 Turbo"}, {ID: "gpt-4.1", Name: "GPT-4.1"}, {ID: "gpt-4.1-mini", Name: "GPT-4.1 Mini"}, {ID: "gpt-4.1-nano", Name: "GPT-4.1 Nano"}, {ID: "o3", Name: "O3"}, {ID: "o3-mini", Name: "O3 Mini"}, {ID: "o3-pro", Name: "O3 Pro"}, {ID: "o4-mini", Name: "O4 Mini"}, {ID: "o1", Name: "O1"}, {ID: "o1-mini", Name: "O1 Mini"}, {ID: "text-embedding-3-large", Name: "Text Embedding 3 Large"}, {ID: "text-embedding-3-small", Name: "Text Embedding 3 Small"}, {ID: "text-embedding-ada-002", Name: "Text Embedding Ada 002"}, {ID: "tts-1", Name: "TTS-1"}, {ID: "tts-1-hd", Name: "TTS-1 HD"}, {ID: "gpt-4o-mini-tts", Name: "GPT-4o Mini TTS"}, {ID: "whisper-1", Name: "Whisper 1"}, {ID: "gpt-4o-transcribe", Name: "GPT-4o Transcribe"}, {ID: "gpt-4o-mini-transcribe", Name: "GPT-4o Mini Transcribe"}, {ID: "gpt-image-1", Name: "GPT Image 1"}, {ID: "dall-e-3", Name: "DALL-E 3"}, {ID: "dall-e-2", Name: "DALL-E 2"}},
	"opencode-go":       {{ID: "glm-5.2", Name: "GLM 5.2"}, {ID: "glm-5.1", Name: "GLM 5.1"}, {ID: "kimi-k2.7-code", Name: "Kimi K2.7 Code"}, {ID: "kimi-k2.6", Name: "Kimi K2.6"}, {ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash"}, {ID: "mimo-v2.5", Name: "MiMo V2.5"}, {ID: "mimo-v2.5-pro", Name: "MiMo V2.5 Pro"}, {ID: "minimax-m3", Name: "MiniMax M3"}, {ID: "minimax-m2.7", Name: "MiniMax M2.7"}, {ID: "minimax-m2.5", Name: "MiniMax M2.5"}, {ID: "qwen3.7-max", Name: "Qwen 3.7 Max"}, {ID: "qwen3.7-plus", Name: "Qwen 3.7 Plus"}, {ID: "qwen3.6-plus", Name: "Qwen 3.6 Plus"}},
	"openrouter":        {{ID: "openai/text-embedding-3-large", Name: "OpenAI Text Embedding 3 Large"}, {ID: "openai/text-embedding-3-small", Name: "OpenAI Text Embedding 3 Small"}, {ID: "openai/text-embedding-ada-002", Name: "OpenAI Text Embedding Ada 002"}, {ID: "qwen/qwen3-embedding-8b", Name: "Qwen3 Embedding 8B"}, {ID: "perplexity/pplx-embed-v1-4b", Name: "Perplexity Embed V1 4B"}, {ID: "perplexity/pplx-embed-v1-0.6b", Name: "Perplexity Embed V1 0.6B"}, {ID: "nvidia/llama-nemotron-embed-vl-1b-v2:free", Name: "NVIDIA Nemotron Embed VL 1B V2 (Free)"}, {ID: "openai/gpt-4o-mini-tts", Name: "GPT-4o Mini TTS"}, {ID: "openai/tts-1-hd", Name: "TTS-1 HD"}, {ID: "openai/tts-1", Name: "TTS-1"}, {ID: "openai/dall-e-3", Name: "DALL-E 3 (via OpenRouter)"}, {ID: "openai/gpt-image-1", Name: "GPT Image 1 (via OpenRouter)"}, {ID: "google/imagen-3.0-generate-002", Name: "Imagen 3 (via OpenRouter)"}, {ID: "black-forest-labs/FLUX.1-schnell", Name: "FLUX.1 Schnell (via OpenRouter)"}},
	"perplexity":        {{ID: "sonar-pro", Name: "Sonar Pro"}, {ID: "sonar", Name: "Sonar"}},
	"poolside":          {{ID: "poolside/laguna-s-2.1", Name: "Laguna S 2.1"}, {ID: "poolside/laguna-xs-2.1", Name: "Laguna XS 2.1"}},
	"perplexity-agent":  {{ID: "perplexity/sonar", Name: "Perplexity Sonar"}, {ID: "openai/gpt-5.5", Name: "GPT-5.5"}, {ID: "openai/gpt-5.4", Name: "GPT-5.4"}, {ID: "openai/gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "anthropic/claude-sonnet-4-6", Name: "Claude Sonnet 4.6"}, {ID: "anthropic/claude-opus-4-8", Name: "Claude Opus 4.8"}, {ID: "google/gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro"}, {ID: "xai/grok-4.20-reasoning", Name: "Grok 4.20 Reasoning"}, {ID: "perplexity/glm-5.2", Name: "GLM 5.2"}, {ID: "perplexity/kimi-k2.7-code", Name: "Kimi K2.7 Code"}, {ID: "nvidia/nemotron-3-super-120b-a12b", Name: "Nemotron 3 Super 120B"}},
	"perplexity-web":    {{ID: "pplx-auto", Name: "Perplexity Auto (Free)"}, {ID: "pplx-sonar", Name: "Perplexity Sonar"}, {ID: "pplx-gpt", Name: "GPT-5.4 (via Perplexity)"}, {ID: "pplx-gemini", Name: "Gemini 3.1 Pro (via Perplexity)"}, {ID: "pplx-sonnet", Name: "Claude Sonnet 4.6 (via Perplexity)"}, {ID: "pplx-opus", Name: "Claude Opus 4.6 (via Perplexity)"}, {ID: "pplx-nemotron", Name: "Nemotron 3 Super (via Perplexity)"}},
	"qoder":             {{ID: "auto", Name: "Qoder Auto"}, {ID: "ultimate", Name: "Qoder Ultimate"}, {ID: "performance", Name: "Qoder Performance"}, {ID: "efficient", Name: "Qoder Efficient"}, {ID: "lite", Name: "Qoder Lite"}, {ID: "qmodel", Name: "Qwen 3.6 Plus (Qoder)"}, {ID: "qmodel_latest", Name: "Qoder Qwen 3.7 Max"}, {ID: "dmodel", Name: "DeepSeek V4 Pro (Qoder)"}, {ID: "dfmodel", Name: "DeepSeek V4 Flash (Qoder)"}, {ID: "gm51model", Name: "GLM 5.1 (Qoder)"}, {ID: "kmodel", Name: "Kimi K2.6 (Qoder)"}, {ID: "mmodel", Name: "MiniMax M2.7 (Qoder)"}},
	"qwen":              {{ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "qwen3-coder-flash", Name: "Qwen3 Coder Flash"}, {ID: "vision-model", Name: "Qwen3 Vision Model"}, {ID: "coder-model", Name: "Qwen3.6 Coder Model"}},
	"recraft":           {{ID: "recraftv3", Name: "Recraft V3"}, {ID: "recraftv2", Name: "Recraft V2"}},
	"runwayml":          {{ID: "gen4_image", Name: "Gen-4 Image"}, {ID: "gen4_image_turbo", Name: "Gen-4 Image Turbo"}, {ID: "gen4_turbo", Name: "Gen-4 Turbo"}, {ID: "gen3a_turbo", Name: "Gen-3 Alpha Turbo"}},
	"sambanova":         {{ID: "MiniMax-M2.7", Name: "MiniMax M2.7"}},
	"sdwebui":           {{ID: "stable-diffusion-v1-5", Name: "Stable Diffusion v1.5"}, {ID: "sdxl-base-1.0", Name: "SDXL Base 1.0"}},
	"siliconflow":       {{ID: "deepseek-ai/DeepSeek-V4-Pro", Name: "DeepSeek V4 Pro"}, {ID: "deepseek-ai/DeepSeek-V4-Flash", Name: "DeepSeek V4 Flash"}, {ID: "deepseek-ai/DeepSeek-V3.2", Name: "DeepSeek V3.2"}, {ID: "deepseek-ai/DeepSeek-V3.2-Exp", Name: "DeepSeek V3.2 Exp"}, {ID: "deepseek-ai/DeepSeek-V3.1", Name: "DeepSeek V3.1"}, {ID: "deepseek-ai/DeepSeek-V3.1-Terminus", Name: "DeepSeek V3.1 Terminus"}, {ID: "deepseek-ai/DeepSeek-R1", Name: "DeepSeek R1"}, {ID: "Qwen/Qwen3.5-397B-A17B", Name: "Qwen 3.5 397B A17B"}, {ID: "Qwen/Qwen3.5-122B-A10B", Name: "Qwen 3.5 122B A10B"}, {ID: "zai-org/GLM-5.1", Name: "GLM 5.1"}, {ID: "zai-org/GLM-5", Name: "GLM 5"}, {ID: "moonshotai/Kimi-K2.6", Name: "Kimi K2.6"}, {ID: "moonshotai/Kimi-K2.5", Name: "Kimi K2.5"}, {ID: "openai/gpt-oss-120b", Name: "GPT OSS 120B"}, {ID: "MiniMaxAI/MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "inclusionAI/Ling-flash-2.0", Name: "Ling Flash 2.0"}},
	"stability-ai":      {{ID: "stable-image-ultra", Name: "Stable Image Ultra"}, {ID: "stable-image-core", Name: "Stable Image Core"}, {ID: "sd3.5-large", Name: "Stable Diffusion 3.5 Large"}, {ID: "sd3.5-large-turbo", Name: "Stable Diffusion 3.5 Large Turbo"}, {ID: "sd3.5-medium", Name: "Stable Diffusion 3.5 Medium"}},
	"tencent":           {{ID: "hunyuan-turbos-latest", Name: "Hunyuan TurboS Latest"}, {ID: "hunyuan-t1-latest", Name: "Hunyuan T1 Latest"}},
	"together":          {{ID: "meta-llama/Llama-3.3-70B-Instruct-Turbo", Name: "Llama 3.3 70B Turbo"}, {ID: "deepseek-ai/DeepSeek-R1", Name: "DeepSeek R1"}, {ID: "Qwen/Qwen3-235B-A22B", Name: "Qwen3 235B"}, {ID: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", Name: "Llama 4 Maverick"}, {ID: "BAAI/bge-large-en-v1.5", Name: "BGE Large EN v1.5"}, {ID: "togethercomputer/m2-bert-80M-8k-retrieval", Name: "M2 BERT 80M 8K"}},
	"venice":            {{ID: "venice-uncensored-1-2", Name: "Venice Uncensored 1.2"}, {ID: "zai-org-glm-5", Name: "GLM-5"}, {ID: "qwen3-235b-a22b-instruct-2507", Name: "Qwen3 235B A22B Instruct"}, {ID: "qwen3-coder-480b-a35b-instruct-turbo", Name: "Qwen3 Coder 480B A35B Turbo"}, {ID: "qwen3-vl-235b-a22b", Name: "Qwen3 VL 235B A22B"}, {ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro"}, {ID: "llama-3.3-70b", Name: "Llama 3.3 70B"}, {ID: "hermes-3-llama-3.1-405b", Name: "Hermes 3 Llama 3.1 405B"}, {ID: "mistral-small-3-2-24b-instruct", Name: "Mistral Small 3.2 24B"}, {ID: "text-embedding-3-large", Name: "Text Embedding 3 Large"}, {ID: "text-embedding-bge-m3", Name: "BGE-M3 Embedding"}, {ID: "text-embedding-qwen3-8b", Name: "Qwen3 8B Embedding"}, {ID: "venice-sd35", Name: "Venice SD3.5"}, {ID: "flux-2-pro", Name: "FLUX.2 Pro"}, {ID: "gpt-image-2", Name: "GPT Image 2 (via Venice)"}},
	"vertex":            {{ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview"}, {ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}},
	"vertex-partner":    {{ID: "deepseek-ai/deepseek-v3.2-maas", Name: "DeepSeek V3.2 (Vertex)"}, {ID: "qwen/qwen3-next-80b-a3b-thinking-maas", Name: "Qwen3 Next 80B Thinking (Vertex)"}, {ID: "qwen/qwen3-next-80b-a3b-instruct-maas", Name: "Qwen3 Next 80B Instruct (Vertex)"}, {ID: "zai-org/glm-5-maas", Name: "GLM-5 (Vertex)"}},
	"volcengine-ark":    {{ID: "Doubao-Seed-2.0-Code", Name: "Doubao-Seed-2.0-Code"}, {ID: "Doubao-Seed-2.0-pro", Name: "Doubao-Seed-2.0-pro"}, {ID: "Doubao-Seed-2.0-lite", Name: "Doubao-Seed-2.0-lite"}, {ID: "Doubao-Seed-Code", Name: "Doubao-Seed-Code"}, {ID: "DeepSeek-V4-Flash", Name: "DeepSeek-V4-Flash"}, {ID: "DeepSeek-V4-Pro", Name: "DeepSeek-V4-Pro"}, {ID: "GLM-5.1", Name: "GLM-5.1"}, {ID: "MiniMax-M2.7", Name: "MiniMax-M2.7"}, {ID: "Kimi-K2.6", Name: "Kimi-K2.6"}},
	"voyage-ai":         {{ID: "voyage-3-large", Name: "Voyage 3 Large"}, {ID: "voyage-3.5", Name: "Voyage 3.5"}, {ID: "voyage-3.5-lite", Name: "Voyage 3.5 Lite"}, {ID: "voyage-code-3", Name: "Voyage Code 3"}, {ID: "voyage-finance-2", Name: "Voyage Finance 2"}, {ID: "voyage-law-2", Name: "Voyage Law 2"}, {ID: "voyage-multilingual-2", Name: "Voyage Multilingual 2"}},
	"xai":               {{ID: "grok-4", Name: "Grok 4"}, {ID: "grok-4-fast-reasoning", Name: "Grok 4 Fast Reasoning"}, {ID: "grok-code-fast-1", Name: "Grok Code Fast"}, {ID: "grok-3", Name: "Grok 3"}, {ID: "grok-2-image-1212", Name: "Grok 2 Image"}, {ID: "grok-imagine-video", Name: "Grok Imagine Video"}},
	"xiaomi-mimo":       {{ID: "mimo-v2.5-pro", Name: "MiMo V2.5 Pro"}, {ID: "mimo-v2.5", Name: "MiMo V2.5"}, {ID: "mimo-v2-omni", Name: "MiMo V2 Omni"}, {ID: "mimo-v2-flash", Name: "MiMo V2 Flash"}},
	"xiaomi-tokenplan":  {{ID: "mimo-v2.5-pro", Name: "MiMo V2.5 Pro"}, {ID: "mimo-v2.5-pro-claude", Name: "MiMo V2.5 Pro (Claude Native)"}, {ID: "mimo-v2.5", Name: "MiMo V2.5"}, {ID: "mimo-v2-pro", Name: "MiMo V2 Pro"}, {ID: "mimo-v2-omni", Name: "MiMo V2 Omni"}, {ID: "mimo-v2-tts", Name: "MiMo V2 TTS"}, {ID: "mimo-v2.5-tts", Name: "MiMo V2.5 TTS"}, {ID: "mimo-v2.5-tts-voiceclone", Name: "MiMo V2.5 TTS Voice Clone"}, {ID: "mimo-v2.5-tts-voicedesign", Name: "MiMo V2.5 TTS Voice Design"}},
}

// GetRegistryModels returns the known registry models for a provider id (may be empty).
func GetRegistryModels(id string) []ModelRef {
	return RegistryModels[id]
}
